astradb:
  collection_name: "e-commerce_chatbot"

embedding_model:
  provider: "google"
  model: "text-embedding-004"

llm_model:
  provider: "google"
  model: "gemini-2.5-pro"

retriever:
  top_k: 3




